Vagrant.configure("2") do |config|

  config.vm.box = "debian/buster64"

  config.vm.define "git_server" do |git_server|
    git_server.vm.provider "virtualbox" do |vb|
       vb.memory = "512"
    end

    git_server.vm.network "private_network", ip: "192.168.33.13"
    git_server.vm.hostname = 'git-server'

    git_server.vm.provision "shell", inline: <<-SHELL
      echo 'Adding SSH KEY'
      echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPfMWrMImmNydYTfDXsxEEmsBRlSVBeToV9wqW8JEGI0' >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

end